### PR TITLE
Use \pocketmine\scheduler\Task instead.

### PR DESCRIPTION
**Pull request by Muqsit**
...since self::getOwner() isn't being used, it's useless.

### CODE REVIEW

**Comment by liam-wiltshire** [comment]
@minecrafter, could you confirm if there is a reason why we are extending from PluginTask please? I did notice in https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/scheduler/Task.php#L25 that it advises extending PluginTask, however as I've not spent much time with the codebase to this point, I'm not sure if this applies in this instance.

**Comment by minecrafter** [comment]
I am erring on the side of caution by following the advice in `Task.php` to use `PluginTask`. I don't have much experience with PocketMine myself, however.

**Comment by minecrafter** [comment]
After closer investigation, I've decided to **reject** this pull request. This could interfere with server functionality, and in any event, the original code is fine.

**Comment by Muqsit** [comment]
Then in that case, it would be better if $this->getOwner() is going to be used instead of BuycraftPlugin::getInstance() in onRun($tick)

**Comment by minecrafter** [comment]
You are free to open another PR to make that change. Note that there's multiple tasks that BuycraftPM starts, so you would need to check everything that extends `PluginTask`.

**Pull request closed without merging**
