### PR TITLE
Latest API Changes Update. - API 3.0.0-ALPHA7

### PR DESCRIPTION
**Pull request by YaBoiLewis**

### CODE REVIEW

**Comment by liam-wiltshire** [comment]
Hey @YaBoiLewis, thanks for the contribution!

We tried to build and test this, however it crashed against the latest version of PocketMine-MP - I think there are a few more typehints that are missing.

I will try to review next week, otherwise if you get a chance to push another commit in the meantime that'd be great!

**Comment by YaBoiLewis** [comment]
Hi,

Sorry, missed a thing. I tested it on the latest pmmp and it works. Happy coding!

**Comment by YaBoiLewis** [comment]
@liam-wiltshire

**Comment by liam-wiltshire** [comment]
Hi, @YaBoiLewis  thanks for this - just going to give it a quick test here and will merge :)

**Pull request merged**
